version: '3.3'

services:
  web:
    image: react-casino-heist_web
    build:
      context: ./Backend
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app
    expose:
      - "8000"