version: '3.3'

services:
  web:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    command: gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app
    expose:
      - "8000"
    environment:
      - FLASK_ENV=production
    networks:
      - app-network